src/WinkMurder/Bundle/GameBundle/Entity/Game.php
<?php

namespace WinkMurder\Bundle\GameBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass="WinkMurder\Bundle\GameBundle\Entity\GameRepository")
 * @ORM\Table(name="Game", indexes={@ORM\Index(name="finished", columns={"finished", "id"})})
 */
class Game {

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue
     */
    protected $id;

    /**
     * @ORM\ManyToOne(targetEntity="PhotoSet")
     */
    protected $photoSet;

    /**
     * @ORM\OneToMany(targetEntity="Player", mappedBy="game", cascade={"PERSIST", "REMOVE"}, orphanRemoval=true)
     */
    protected $players;

    /**
     * @ORM\ManyToOne(targetEntity="Photo")
     * @ORM\JoinColumn(name="murdererPhoto_id", referencedColumnName="id", onDelete="CASCADE")
     */
    protected $murdererPhoto;

    /**
     * @ORM\OneToMany(targetEntity="Murder", mappedBy="game", cascade={"PERSIST", "REMOVE"}, orphanRemoval=true)
     */
    protected $murders;

    /**
     * @ORM\Column(type="integer")
     */
    protected $requiredPositiveSuspicionRate = 50   ;

    /**
     * @ORM\Column(type="integer")
     */
    protected $durationOfPreliminaryProceedingsInMinutes = 10;

    /**
     * @ORM\Column(type="integer")
     */
    protected $requiredMurders = 15;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $finished = false;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $started = false;

    public function __construct(PhotoSet $photoSet) {
        $this->photoSet = $photoSet;
        $this->players = new ArrayCollection();
        $this->murders = new ArrayCollection();
    }

    public function getId() {
        return $this->id;
    }

    /** @return PhotoSet */
    public function getPhotoSet() {
        return $this->photoSet;
    }

    /** @return Photo[] */
    public function getPhotos() {
        $photos = $this->photoSet->getPhotos();
        usort($photos, function($photoA, $photoB) {
            return strcmp($photoA->getTitle(), $photoB->getTitle());
        });
        return $photos;
    }

    /** @return Photo[] */
    public function getUnusedPhotos() {
        $players = $this->players;
        return array_filter($this->getPhotos(), function(Photo $photo) use ($players) {
            foreach ($players as $player) {
                if ($player->getPhoto() === $photo) {
                    return false;
                }
            }
            return true;
        });
    }

    /** @return Photo */
    public function findUnusedPhoto($id) {
        foreach ($this->getUnusedPhotos() as $unusedPhoto) {
            if ($id == $unusedPhoto->getId()) {
                return $unusedPhoto;
            }
        }
    }

    /** @return Player */
    public function findPlayer($id) {
        foreach ($this->players as $player) {
            if ($player->getId() == $id) {
                return $player;
            }
        }
    }

    /** @return Murder */
    public function findMurderByPlayer(Player $player) {
        foreach ($this->murders as $murder) {
            if ($murder->getVictim() == $player) {
                return $murder;
            }
        }
    }

    /** @return Murder[] */
    public function getMurders() {
        $murders = $this->murders->toArray();
        usort($murders, function(Murder $murderA, Murder $murderB) {
            return intval($murderB->getTimeOfOffense()->format('U')) - intval($murderA->getTimeOfOffense()->format('U'));
        });
        return $murders;
    }

    /** @return Players[] */
    public function getPlayers() {
        $players = $this->players->toArray();
        usort($players, function($playerA, $playerB) {
            return strcmp($playerA->getName(), $playerB->getName());
        });
        return $players;
    }

    /** @return Murder */
    public function getLatestMurderWithPreliminaryProceedingsOngoing() {
        if ($murder = $this->getLatestMurder()) {
            if (!$murder->arePreliminaryProceedingsDiscontinued()) {
                return $murder;
            }
        }
    }

    /** @return Murder */
    public function getLatestMurderWithPreliminaryProceedingsDiscontinued() {
        foreach ($this->getMurders() as $murder) {
            if ($murder->arePreliminaryProceedingsDiscontinued()) {
                return $murder;
            }
        }
    }

    /** @return Murder[] */
    public function getMurdersWithSuspicionOrPreliminaryProceedingsDiscontinued(Player $player) {
        return array_filter($this->getMurders(), function(Murder $murder) use ($player) {
            return $murder->arePreliminaryProceedingsDiscontinued() || $murder->hasSuspicion($player);
        });
    }

    /** @return Murder[] */
    public function getMurdersWithPreliminaryProceedingsDiscontinued() {
        return array_filter($this->getMurders(), function(Murder $murder) {
            return $murder->arePreliminaryProceedingsDiscontinued();
        });
    }

    /** @return Player */
    public function addPlayer(Photo $photo, MannerOfDeath $mannerOfDeath) {
        $player = new Player($this, $photo, $mannerOfDeath);
        $this->players->add($player);
        return $player;
    }

    public function removePlayer(Player $player) {
        $this->players->removeElement($player);
    }

    public function setMurdererPhoto(Photo $photo = null) {
        $this->murdererPhoto = $photo;
    }

    /** @return Photo */
    public function getMurdererPhoto() {
        return $this->murdererPhoto;
    }

    /** @return Player */
    public function getMurderer() {
        return $this->findPlayerByPhoto($this->murdererPhoto);
    }

    /** @return Photos */
    public function getPhotosWithoutAccount() {
        $game = $this;
        return array_filter($this->getPhotos(), function(Photo $photo) use ($game) {
            if ($player = $game->findPlayerByPhoto($photo)) {
                return !$player->getAccount();
            } else {
                return true;
            }
        });
    }

    /** @return Photo */
    public function findPlayerByPhoto(Photo $photo = null) {
        foreach ($this->players as $player) {
            if ($player->getPhoto() == $photo) {
                return $player;
            }
        }
    }

    public function isMurderer(Player $player) {
        return $this->getMurderer() === $player;
    }

    public function canBeKilled(Player $victim) {
        try {
            $this->checkKill($victim);
            return true;
        } catch (\Exception $e) {}
        return false;
    }

    /** @return Players[] */
    public function getOtherPlayers(Player $player = null) {
        return array_filter($this->getPlayers(), function(Player $other) use ($player) {
            return $other !== $player;
        });
    }

    /** @return Players[] */
    public function getAliveOtherPlayers(Player $player = null) {
        return array_filter($this->getAlivePlayers(), function(Player $other) use ($player) {
            return $other !== $player;
        });
    }

    /** @return Players[] */
    public function getAlivePlayers() {
        return array_filter($this->players->toArray(), function(Player $player) {
            return !$player->isDead();
        });
    }

    public function checkKill(Player $victim, Player $murderer = null) {
        if ($this->hasMurdererWon()) throw new \Exception("The murderer has already won.");
        if ($murderer && !$murderer->isMurderer()) throw new \Exception("Player {$murderer->getName()} is not the murderer.");
        if ($victim->isDead()) throw new \Exception("Player {$victim->getName()} is already dead.");
        if ($murderer && ($murderer === $victim)) throw new \Exception("Player {$murderer->getName()} cannot murder himself.");
        if ($victim->isMurderer()) throw new \Exception("The Murderer cannot be killed.");
        if ($this->arePreliminaryProceedingsOngoing()) throw new \Exception("The preliminary proceedings of the last murder are still ongoing.");
        if ($this->isMurdererIdentified()) throw new \Exception("The murderer is identified.");
    }

    public function kill(Player $player, Player $murderer = null, $time = null) {
        $this->checkKill($player, $murderer);
        $this->murders->add(new Murder($this, $player, $time ?: new \DateTime('now')));
    }

    public function resurrect(Player $player) {
        if ($murder = $player->getMurder()) {
            $this->murders->removeElement($murder);
            $player->setMurder(null);
        } else {
            throw new \Exception("Player {$player->getName()} is alive.");
        }
    }

    /** @return Murder */
    public function getLatestMurder() {
        return reset($this->getMurders());
    }

    public function canSuspect(Player $witness, Player $suspect = null) {
        if (!$this->getLatestMurderWithPreliminaryProceedingsOngoing()) return false;
        if ($witness->isDead()) return false;
        if ($this->hasSuspicion($witness)) return false;
        if ($suspect && $suspect->isDead()) return false;
        return true;
    }

    public function hasSuspicion(Player $witness) {
        return $this->getLatestMurder()->hasSuspicion($witness);
    }

    /** @return Suspicion */
    public function getSuspicion(Player $witness) {
        return $this->getLatestMurder()->getSuspicion($witness);
    }

    public function suspect(Player $witness, Player $suspect) {
        if ($this->canSuspect($witness, $suspect)) {
            $this->getLatestMurder()->addSuspicion($witness, $suspect);
        }
    }

    public function isMurdererIdentified() {
        if ($latestMurder = $this->getLatestMurder()) {
            return $latestMurder->isClearedUp();
        }
        return false;
    }

    public function arePreliminaryProceedingsOngoing() {
        if ($latestMurder = $this->getLatestMurder()) {

src/WinkMurder/Bundle/GameBundle/Controller/BaseController.php
<?php

namespace WinkMurder\Bundle\GameBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use WinkMurder\Bundle\GameBundle\Entity\Account;
use WinkMurder\Bundle\GameBundle\Security\GuestAccess;

abstract class BaseController extends Controller {

    /** @return \WinkMurder\Bundle\GameBundle\Entity\AccountRepository */
    protected function getAccountRepository() {
        return $this->getDoctrine()->getRepository('WinkMurderGameBundle:Account');
    }

    /** @return \Symfony\Component\Security\Core\SecurityContextInterface */
    protected function getSecurityContext() {
        return $this->get('security.context');
    }

    /** @return \WinkMurder\Bundle\GameBundle\Entity\Account */
    protected function getAuthenticatedAccount() {
        $user = $this->getSecurityContext()->getToken()->getUser();
        if ($user instanceof Account || $user instanceof GuestAccess)
            return $user;
    }

    /** @return \WinkMurder\Bundle\GameBundle\Entity\Player */
    protected function getAuthenticatedPlayer() {
        if ($account = $this->getAuthenticatedAccount()) {
            return $account->getPlayer();
        }
    }

    /** @return \WinkMurder\Bundle\GameBundle\Entity\Game */
    public function getCurrentGame() {
        return $this->getGameRepository()->findCurrentOne();
    }

    /** @return \WinkMurder\Bundle\GameBundle\Entity\GameRepository */
    protected function getGameRepository() {
        return $this->getDoctrine()->getRepository('WinkMurderGameBundle:Game');
    }

    /** @return \WinkMurder\Bundle\GameBundle\Entity\MannerOfDeathRepository */
    protected function getMannerOfDeathRepository() {
        return $this->getDoctrine()->getRepository('WinkMurderGameBundle:MannerOfDeath');
    }

    /** @return \Doctrine\ORM\EntityRepository */
    protected function getPhotoSetRepository() {
        return $this->getDoctrine()->getRepository('WinkMurderGameBundle:PhotoSet');
    }

    protected function getTranslationRepository() {
        return $this->getDoctrine()->getRepository('Stof\DoctrineExtensionsBundle\Entity\Translation');
    }

    /** @return \Doctrine\ORM\EntityManager */
    protected function getEntityManager() {
        return $this->getDoctrine()->getEntityManager();
    }

}

src/WinkMurder/Bundle/GameBundle/Resources/views/Administration/index.html.twig
{% extends "WinkMurderGameBundle:Common:Layout/_administration.html.twig" %}

{% block pageTitle %}{{ 'administration.index.pageTitle' | trans }}{% endblock %}

{% block content %}
    {% if game %}
        <h2>{{ 'administration.index.currentGame.heading' | trans }}</h2>

        <div data-role="collapsible" data-collapsed-icon="arrow-r" data-expanded-icon="arrow-d"{% if not game.murdererPhoto %} data-collapsed="false"{% endif %}>
            <h3>{{ 'administration.index.currentGame.theMurderer.heading' | trans }}</h3>
            <div>
                {% if game.murdererPhoto %}
                    <p>{{ 'administration.index.currentGame.theMurderer.status' | trans({'%name%': game.murdererPhoto.title}) }} <a href="{{ path('winkmurder_game_administration_selectmurderer') }}" data-ajax="false" data-inline="true" data-mini="true" data-role="button" data-icon="delete">{{ 'administration.index.currentGame.theMurderer.change' | trans }}</a></p>
                {% else %}
                    <p>{{ 'administration.index.currentGame.theMurderer.select' | trans }}</p>
                    <ul data-role="listview" data-inset="true" data-filter="true" data-filter-placeholder="{{ 'administration.index.currentGame.theMurderer.filterPlaceholder' | trans }}">
                    {% for photo in game.photoSet.photos %}
                        <li data-filtertext="{{ photo.title }}">
                            <a href="{{ path('winkmurder_game_administration_selectmurderer', {id: photo.id}) }}" data-ajax="false">
                                {% include "WinkMurderGameBundle:Common:Photo/_teaser.html.twig" %}
                            </a>
                        </li>
                    {% endfor %}
                    </ul>
                {% endif %}
            </div>
        </div>

        <div data-role="collapsible" data-collapsed-icon="arrow-r" data-expanded-icon="arrow-d"{% if game.murdererPhoto %} data-collapsed="false"{% endif %}>
            <h3>{{ 'administration.index.currentGame.players.heading' | trans }}</h3>
            <div>
                {% if game.players %}
                    <ul data-role="listview" data-inset="true" data-filter="true" data-filter-placeholder="{{ 'administration.index.currentGame.players.filterPlaceholder' | trans }}">
                    {% for player in game.players %}
                        <li data-filtertext="{{ player.name }}">
                            <div class="ui-grid-a">
                                <div class="ui-block-a">
                                    {% include "WinkMurderGameBundle:Common:Player/_teaser.html.twig" %}
                                </div>
                                {% if player.dead %}
                                    <div class="ui-block-a">
                                        {{ 'administration.index.currentGame.players.dead' | trans }}
                                    </div>
                                    <div class="ui-block-b">
                                        <form action="{{ path('winkmurder_game_administration_toggledead', {id: player.id}) }}" method="post" data-ajax="false"><div><input type="submit" value="{{ 'administration.index.currentGame.players.resurrect' | trans }}" /></div></form>
                                    </div>
                                {% else %}
                                    <div class="ui-block-b">
                                        <form action="{{ path('winkmurder_game_administration_unauthenticate', {id: player.id}) }}" method="post" data-ajax="false"><div><input type="submit" value="{{ 'administration.index.currentGame.players.unauthenticate' | trans }}" /></div></form>
                                    </div>
                                    {% if game.canBeKilled(player) %}
                                        <div class="ui-block-a">
                                            {{ 'administration.index.currentGame.players.alive' | trans }}
                                        </div>
                                        <div class="ui-block-b">
                                            <form action="{{ path('winkmurder_game_administration_toggledead', {id: player.id}) }}" method="post" data-ajax="false"><div><input type="submit" value="{{ 'administration.index.currentGame.players.kill' | trans }}" /></div></form>
                                        </div>
                                    {% endif %}
                                {% endif %}
                            </div>

                            <form action="{{ path('winkmurder_game_administration_switchphoto', {id: player.id}) }}" method="post" data-ajax="false">
                                <div class="ui-grid-a">
                                    <div class="ui-block-a">
                                        <select name="photo">
                                            <option></option>
                                            {% for photo in game.photoSet.photos %}
                                                {% if not photo is sameas(player.photo) %}
                                                    <option value="{{ photo.id }}">{{ photo.title }}</option>
                                                {% endif %}
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div class="ui-block-b">
                                        <input type="submit" value="{{ 'administration.index.currentGame.players.switchPhoto' | trans }}" />
                                    </div>
                                </div>
                            </form>
                        </li>
                    {% endfor %}
                    </ul>
                {% else %}
                    {{ 'administration.index.currentGame.players.noneYet' | trans }}
                {% endif %}
            </div>
        </div>

        <div data-role="collapsible" data-collapsed-icon="arrow-r" data-expanded-icon="arrow-d">
            <h3>{{ 'administration.index.currentGame.unusedPhotos.heading' | trans }}</h3>
            <div>
                {% if game.unusedPhotos %}
                    <ul data-role="listview" data-inset="true" data-filter="true" data-filter-placeholder="{{ 'administration.index.currentGame.unusedPhotos.filterPlaceholder' | trans }}">
                    {% for photo in game.unusedPhotos %}
                        <li data-filtertext="{{ photo.title }}">
                            <div>
                                {{ photo.title }}
                            </div>
                            <div>
                                <img src="{{ photo.url }}" alt="{{ photo.title }}" />
                            </div>
                        </li>
                    {% endfor %}
                    </ul>
                {% else %}
                    {{ 'administration.index.currentGame.unusedPhotos.noneLeft' | trans }}
                {% endif %}
            </div>
        </div>

        <div data-role="collapsible" data-collapsed-icon="arrow-r" data-expanded-icon="arrow-d">
            <h3>{{ 'administration.index.currentGame.start.heading' | trans }}</h3>
            {% if game.started %}
                <p>{{ 'administration.index.currentGame.start.alreadyStarted' | trans }}</p>
            {% else %}
                <div>
                    <form action="{{ path('winkmurder_game_administration_startgame') }}" method="post" data-ajax="false"><div><input type="submit" value="{{ 'administration.index.currentGame.start.submit' | trans }}" data-inline="true" /></div></form>
                </div>
            {% endif %}
        </div>

        <div data-role="collapsible" data-collapsed-icon="arrow-r" data-expanded-icon="arrow-d">
            <h3>{{ 'administration.index.currentGame.settings.heading' | trans }}</h3>
            <div>
                <form action="{{ path('winkmurder_game_administration_updatesettings') }}" method="post" data-ajax="false">
                    {{ form_widget(settingsForm) }}
                    <div><input type="submit" value="{{ 'administration.index.currentGame.settings.form.submit' | trans }}" data-inline="true" /></div>
                </form>
            </div>
        </div>

        <div data-role="collapsible" data-collapsed-icon="arrow-r" data-expanded-icon="arrow-d">
            <h3>{{ 'administration.index.currentGame.delete.heading' | trans }}</h3>
            <div>
                <p>{{ 'administration.index.currentGame.delete.warning' | trans }}</p>
                <form action="{{ path('winkmurder_game_administration_deletegame') }}" method="post" data-ajax="false"><div><input type="submit" value="{{ 'administration.index.currentGame.delete.submit' | trans }}" data-inline="true" /></div></form>
            </div>
        </div>

        <h2>{{ 'administration.index.general.heading' | trans }}</h2>
    {% endif %}

    <div data-role="collapsible" data-expanded-icon="add" data-collapsed-icon="add"{% if not game %} data-collapsed="false"{% endif %}>
        <h3>{{ 'administration.index.general.createNewGame.heading' | trans }}</h3>
        <div>
            {% if photoSets and mannersOfDeath %}
                {% if game %}<p>{{ 'administration.index.general.createNewGame.warning' | trans }}</p>{% endif %}
                <form action="{{ path('winkmurder_game_administration_createnewgame') }}" method="post" data-ajax="false">
                    <div data-role="fieldcontain">
                        <label for="photoSet">{{ 'administration.index.general.createNewGame.photoset' | trans }}</label>
                        <select name="id" id="photoSet">
                            <option></option>
                            {% for photoSet in photoSets %}
                                <option value="{{ photoSet.id }}">{{ photoSet.title }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div>
                        <input type="submit" value="{{ 'administration.index.general.createNewGame.submit' | trans }}" data-inline="true" />
                    </div>
                </form>
            {% else %}
                {{ 'administration.index.general.noPhotosetsOrManners' | trans }}
            {% endif %}
        </div>
    </div>

    <div data-role="collapsible" data-expanded-icon="refresh" data-collapsed-icon="refresh">
        <h3>{{ 'administration.index.general.synchronizePhotosets.heading' | trans }}</h3>
        <div>
            {% if not photoSets %}
                <p>{{ 'administration.index.general.synchronizePhotosets.noneYet' | trans }}</p>
            {% else %}
                <p>{{ 'administration.index.general.synchronizePhotosets.update' | trans }}</p>
            {% endif %}
            <form action="{{ path('winkmurder_game_administration_synchronizephotosets') }}" method="post" data-ajax="false">
                <div>
                    <input type="submit" value="{{ 'administration.index.general.synchronizePhotosets.submit' | trans }}" data-inline="true" />
                </div>
            </form>
        </div>
    </div>

    <div data-role="collapsible" data-expanded-icon="refresh" data-collapsed-icon="refresh">
        <h3>{{ 'administration.index.general.mannersOfDeath.heading' | trans }}</h3>
        <div>
            <div>{{ 'administration.index.general.mannersOfDeath.status' | trans({'%count%': mannersOfDeath | length }) }}</div>
            <div><a href="{{ path('winkmurder_game_mannerofdeath_index') }}" data-role="button" data-ajax="false" data-inline="true">{{ 'administration.index.general.mannersOfDeath.link' | trans }}</a></div>
        </div>
    </div>
{% endblock %}

src/WinkMurder/Bundle/GameBundle/Resources/views/Administration/login.html.twig
{% extends "WinkMurderGameBundle:Common:Layout/_administration.html.twig" %}

{% block pageTitle %}{{ 'administration.login.pageTitle' | trans }}{% endblock %}

{% block content %}
    <h2>{{ 'administration.login.heading' | trans }}</h2>
    {% include "WinkMurderGameBundle:Common:Login/_loginForm.html.twig" with {action: path('winkmurder_game_administration_logincheck')} %}
{% endblock %}