src/WinkMurder/Bundle/GameBundle/Entity/Game.php
<?php

namespace WinkMurder\Bundle\GameBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass="WinkMurder\Bundle\GameBundle\Entity\GameRepository")
 * @ORM\Table(name="Game", indexes={@ORM\Index(name="finished", columns={"finished", "id"})})
 */
class Game {

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue
     */
    protected $id;

    /**
     * @ORM\ManyToOne(targetEntity="PhotoSet")
     */
    protected $photoSet;

    /**
     * @ORM\OneToMany(targetEntity="Player", mappedBy="game", cascade={"PERSIST", "REMOVE"}, orphanRemoval=true)
     */
    protected $players;

    /**
     * @ORM\ManyToOne(targetEntity="Photo")
     * @ORM\JoinColumn(name="murdererPhoto_id", referencedColumnName="id", onDelete="CASCADE")
     */
    protected $murdererPhoto;

    /**
     * @ORM\OneToMany(targetEntity="Murder", mappedBy="game", cascade={"PERSIST", "REMOVE"}, orphanRemoval=true)
     */
    protected $murders;

    /**
     * @ORM\Column(type="integer")
     */
    protected $requiredPositiveSuspicionRate = 50   ;

    /**
     * @ORM\Column(type="integer")
     */
    protected $durationOfPreliminaryProceedingsInMinutes = 10;

    /**
     * @ORM\Column(type="integer")
     */
    protected $requiredMurders = 15;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $finished = false;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $started = false;

    public function __construct(PhotoSet $photoSet) {
        $this->photoSet = $photoSet;
        $this->players = new ArrayCollection();
        $this->murders = new ArrayCollection();
    }

    public function getId() {
        return $this->id;
    }

    /** @return PhotoSet */
    public function getPhotoSet() {
        return $this->photoSet;
    }

    /** @return Photo[] */
    public function getPhotos() {
        $photos = $this->photoSet->getPhotos();
        usort($photos, function($photoA, $photoB) {
            return strcmp($photoA->getTitle(), $photoB->getTitle());
        });
        return $photos;
    }

    /** @return Photo[] */
    public function getUnusedPhotos() {
        $players = $this->players;
        return array_filter($this->getPhotos(), function(Photo $photo) use ($players) {
            foreach ($players as $player) {
                if ($player->getPhoto() === $photo) {
                    return false;
                }
            }
            return true;
        });
    }

    /** @return Photo */
    public function findUnusedPhoto($id) {
        foreach ($this->getUnusedPhotos() as $unusedPhoto) {
            if ($id == $unusedPhoto->getId()) {
                return $unusedPhoto;
            }
        }
    }

    /** @return Player */
    public function findPlayer($id) {
        foreach ($this->players as $player) {
            if ($player->getId() == $id) {
                return $player;
            }
        }
    }

    /** @return Murder */
    public function findMurderByPlayer(Player $player) {
        foreach ($this->murders as $murder) {
            if ($murder->getVictim() == $player) {
                return $murder;
            }
        }
    }

    /** @return Murder[] */
    public function getMurders() {
        $murders = $this->murders->toArray();
        usort($murders, function(Murder $murderA, Murder $murderB) {
            return intval($murderB->getTimeOfOffense()->format('U')) - intval($murderA->getTimeOfOffense()->format('U'));
        });
        return $murders;
    }

    /** @return Players[] */
    public function getPlayers() {
        $players = $this->players->toArray();
        usort($players, function($playerA, $playerB) {
            return strcmp($playerA->getName(), $playerB->getName());
        });
        return $players;
    }

    /** @return Murder */
    public function getLatestMurderWithPreliminaryProceedingsOngoing() {
        if ($murder = $this->getLatestMurder()) {
            if (!$murder->arePreliminaryProceedingsDiscontinued()) {
                return $murder;
            }
        }
    }

    /** @return Murder */
    public function getLatestMurderWithPreliminaryProceedingsDiscontinued() {
        foreach ($this->getMurders() as $murder) {
            if ($murder->arePreliminaryProceedingsDiscontinued()) {
                return $murder;
            }
        }
    }

    /** @return Murder[] */
    public function getMurdersWithSuspicionOrPreliminaryProceedingsDiscontinued(Player $player) {
        return array_filter($this->getMurders(), function(Murder $murder) use ($player) {
            return $murder->arePreliminaryProceedingsDiscontinued() || $murder->hasSuspicion($player);
        });
    }

    /** @return Murder[] */
    public function getMurdersWithPreliminaryProceedingsDiscontinued() {
        return array_filter($this->getMurders(), function(Murder $murder) {
            return $murder->arePreliminaryProceedingsDiscontinued();
        });
    }

    /** @return Player */
    public function addPlayer(Photo $photo, MannerOfDeath $mannerOfDeath) {
        $player = new Player($this, $photo, $mannerOfDeath);
        $this->players->add($player);
        return $player;
    }

    public function removePlayer(Player $player) {
        $this->players->removeElement($player);
    }

    public function setMurdererPhoto(Photo $photo = null) {
        $this->murdererPhoto = $photo;
    }

    /** @return Photo */
    public function getMurdererPhoto() {
        return $this->murdererPhoto;
    }

    /** @return Player */
    public function getMurderer() {
        return $this->findPlayerByPhoto($this->murdererPhoto);
    }

    /** @return Photos */
    public function getPhotosWithoutAccount() {
        $game = $this;
        return array_filter($this->getPhotos(), function(Photo $photo) use ($game) {
            if ($player = $game->findPlayerByPhoto($photo)) {
                return !$player->getAccount();
            } else {
                return true;
            }
        });
    }

    /** @return Photo */
    public function findPlayerByPhoto(Photo $photo = null) {
        foreach ($this->players as $player) {
            if ($player->getPhoto() == $photo) {
                return $player;
            }
        }
    }

    public function isMurderer(Player $player) {
        return $this->getMurderer() === $player;
    }

    public function canBeKilled(Player $victim) {
        try {
            $this->checkKill($victim);
            return true;
        } catch (\Exception $e) {}
        return false;
    }

    /** @return Players[] */
    public function getOtherPlayers(Player $player = null) {
        return array_filter($this->getPlayers(), function(Player $other) use ($player) {
            return $other !== $player;
        });
    }

    /** @return Players[] */
    public function getAliveOtherPlayers(Player $player = null) {
        return array_filter($this->getAlivePlayers(), function(Player $other) use ($player) {
            return $other !== $player;
        });
    }

    /** @return Players[] */
    public function getAlivePlayers() {
        return array_filter($this->players->toArray(), function(Player $player) {
            return !$player->isDead();
        });
    }

    public function checkKill(Player $victim, Player $murderer = null) {
        if ($this->hasMurdererWon()) throw new \Exception("The murderer has already won.");
        if ($murderer && !$murderer->isMurderer()) throw new \Exception("Player {$murderer->getName()} is not the murderer.");
        if ($victim->isDead()) throw new \Exception("Player {$victim->getName()} is already dead.");
        if ($murderer && ($murderer === $victim)) throw new \Exception("Player {$murderer->getName()} cannot murder himself.");
        if ($victim->isMurderer()) throw new \Exception("The Murderer cannot be killed.");
        if ($this->arePreliminaryProceedingsOngoing()) throw new \Exception("The preliminary proceedings of the last murder are still ongoing.");
        if ($this->isMurdererIdentified()) throw new \Exception("The murderer is identified.");
    }

    public function kill(Player $player, Player $murderer = null, $time = null) {
        $this->checkKill($player, $murderer);
        $this->murders->add(new Murder($this, $player, $time ?: new \DateTime('now')));
    }

    public function resurrect(Player $player) {
        if ($murder = $player->getMurder()) {
            $this->murders->removeElement($murder);
            $player->setMurder(null);
        } else {
            throw new \Exception("Player {$player->getName()} is alive.");
        }
    }

    /** @return Murder */
    public function getLatestMurder() {
        return reset($this->getMurders());
    }

    public function canSuspect(Player $witness, Player $suspect = null) {
        if (!$this->getLatestMurderWithPreliminaryProceedingsOngoing()) return false;
        if ($witness->isDead()) return false;
        if ($this->hasSuspicion($witness)) return false;
        if ($suspect && $suspect->isDead()) return false;
        return true;
    }

    public function hasSuspicion(Player $witness) {
        return $this->getLatestMurder()->hasSuspicion($witness);
    }

    /** @return Suspicion */
    public function getSuspicion(Player $witness) {
        return $this->getLatestMurder()->getSuspicion($witness);
    }

    public function suspect(Player $witness, Player $suspect) {
        if ($this->canSuspect($witness, $suspect)) {
            $this->getLatestMurder()->addSuspicion($witness, $suspect);
        }
    }

    public function isMurdererIdentified() {
        if ($latestMurder = $this->getLatestMurder()) {
            return $latestMurder->isClearedUp();
        }
        return false;
    }

    public function arePreliminaryProceedingsOngoing() {
        if ($latestMurder = $this->getLatestMurder()) {

src/WinkMurder/Bundle/GameBundle/Form/GameForm.php
<?php

namespace WinkMurder\Bundle\GameBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class GameForm extends AbstractType {

    public function getName() {
        return 'game';
    }

    public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder->add('requiredPositiveSuspicionRate', 'integer', array('label' => 'administration.index.currentGame.settings.form.requiredPositiveSuspicionRate'));
        $builder->add('durationOfPreliminaryProceedingsInMinutes', 'integer', array('label' => 'administration.index.currentGame.settings.form.durationOfPreliminaryProceedingsInMinutes'));
        $builder->add('requiredMurders', 'integer', array('label' => 'administration.index.currentGame.settings.form.requiredMurders'));
    }

}

src/WinkMurder/Bundle/GameBundle/Controller/GameController.php
<?php

namespace WinkMurder\Bundle\GameBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;

/**
 * @Route("/game")
 */
class GameController extends BaseController {

    /**
     * @Route("/")
     */
    public function indexAction() {
        $game = $this->getCurrentGame();
        if ($game && $game->isStarted()) {
            if ($this->getAuthenticatedPlayer()) {
                return $this->redirect($this->generateUrl('winkmurder_game_game_status'));
            } else {
                return $this->redirect($this->generateUrl('winkmurder_game_game_players'));
            }
        } else {
            return $this->redirect($this->generateUrl('winkmurder_game_game_story'));
        }
    }

    /**
     * @Route("/status/")
     * @Template
     */
    public function statusAction() {
        return array('game' => $this->getCurrentGame());
    }

    /**
     * @Route("/players/")
     * @Template
     */
    public function playersAction() {
        return array('game' => $this->getCurrentGame());
    }

    /**
     * @Route("/rules/")
     * @Template
     */
    public function rulesAction() {
        return array('game' => $this->getCurrentGame());
    }

    /**
     * @Route("/story/")
     * @Template
     */
    public function storyAction() {
        return array('game' => $this->getCurrentGame());
    }

    /**
     * @Route("/commit-murder/{id}/")
     * @Template
     */
    public function commitMurderAction($id) {
        if ($victim = $this->getCurrentGame()->findPlayer($id)) {
            if ($this->getAuthenticatedPlayer()->canMurder($victim)) {
                return array('victim' => $victim);
            }
        }
        return $this->redirect($this->generateUrl('winkmurder_game_game_players'));
    }

    /**
     * @Route("/commit-murder/{id}/confirm/")
     * @Method("POST")
     */
    public function confirmCommitMurderAction($id) {
        try {
            $this->getAuthenticatedPlayer()->murder(
                $this->getCurrentGame()->findPlayer($id)
            );
            $this->getEntityManager()->flush();
        } catch (\Exceptions $e) {
        }
        return $this->redirect($this->generateUrl('winkmurder_game_game_status'));
    }

}

src/WinkMurder/Bundle/GameBundle/Resources/views/Game/status/_mostPopularDeath.html.twig
{% if game.mostPopularDeath %}
    <div class="centered">
        <p class="mrgn-btm-6">{{ 'game.mostPopularDeath' | trans }}</p>
        <p class="jollylodger type-big block">{{ game.mostPopularDeath.victim.name }}</p>
    </div>
{% endif %}

src/WinkMurder/Bundle/GameBundle/Resources/views/Game/status/_murdererLost.html.twig
<div class="centered mrgn-btm-24">
    <p class="type-big imfellsc mrgn-top-24 mrgn-btm-24">{{ 'game.status.murdererLost.heading' | trans }}</p>
    <img src="{{ game.murderer.photo.url }}" alt="{{ game.murderer.photo.title }}" width="60" class="profile-thumb" />
    <p class="type-huge highlighted jollylodger">{{ 'game.status.murdererLost.convict' | trans({'%murderer%': game.murderer.name}) }}</p>
</div>
{% include "WinkMurderGameBundle:Game:status/_mostPopularDeath.html.twig" %}

src/WinkMurder/Bundle/GameBundle/Resources/views/Game/status/_murdererStillAtLarge.html.twig
{% include "WinkMurderGameBundle:Common:Murder/_latestMurderTeaser.html.twig" with {'murder': game.latestMurderWithPreliminaryProceedingsDiscontinued} %}

{% if game.arePreliminaryProceedingsOngoing %}

    {% if app.user %}
        <p class="centered wm-button">
            <a data-role="button" data-inline="true" href="{{ path('winkmurder_game_investigations_index') }}">
                {{ 'game.status.murdererStillAtLarge.investigationsLink' | trans }}
            </a>
        </p>
    {% endif %}

{% else %}

    {% set templates = [
        "WinkMurderGameBundle:Game:status/notClearedUpReasons/_atLarge.html.twig",
        "WinkMurderGameBundle:Game:status/notClearedUpReasons/_404.html.twig",
        "WinkMurderGameBundle:Game:status/notClearedUpReasons/_alibi.html.twig"
    ] %}

    {% set which = game.latestMurder.id %} {# Für jeden Spieler je Tod ein neuer Grund #}
    {# {% set which = 0 %} {# Zum Testen: ein bestimtes #}
    {# {% set which = random(templates | length) %} {# Zum Testen: ein zufälliges #}

    {% include cycle(templates, which) %}

{% endif %}

src/WinkMurder/Bundle/GameBundle/Resources/views/Game/status/_murdererWon.html.twig
<div class="centered mrgn-btm-24">
    <p class="type-big imfellsc mrgn-top-24 mrgn-btm-24">{{ 'game.status.murdererWon.heading' | trans }}</p>
    <img src="{{ game.murderer.photo.url }}" alt="{{ game.murderer.photo.title }}" width="60" class="profile-thumb" />
    <p class="type-huge highlighted jollylodger">{{ 'game.status.murdererWon.convict' | trans({'%murderer%': game.murderer.name}) }}</p>
</div>
{% include "WinkMurderGameBundle:Game:status/_mostPopularDeath.html.twig" %}

src/WinkMurder/Bundle/GameBundle/Resources/views/Game/status/_noMurderYet.html.twig
<div class="centered">
    <h1>{{ 'game.status.noMurderYet.heading' | trans }}</h1>
    <p>{{ 'game.status.noMurderYet.text' | trans }}</p>
</div>

src/WinkMurder/Bundle/GameBundle/Resources/views/Game/status/murdererLost.html.twig
<div class="centered mrgn-btm-24">
    <p class="type-big imfellsc mrgn-top-24 mrgn-btm-24">{{ 'game.status.murdererLost.heading' | trans }}</p>
    <img src="{{ game.murderer.photo.url }}" alt="{{ game.murderer.photo.title }}" width="60" class="profile-thumb" />
    <p class="type-huge highlighted jollylodger">{{ 'game.status.murdererLost.convict' | trans({'%murderer%': game.murderer.name}) }}</p>
</div>
{% include "WinkMurderGameBundle:Game:status/_mostPopularDeath.html.twig" %}

src/WinkMurder/Bundle/GameBundle/Resources/views/Game/status/murdererWon.html.twig
<div class="centered mrgn-btm-24">
    <p class="type-big imfellsc mrgn-top-24 mrgn-btm-24">{{ 'game.status.murdererWon.heading' | trans }}</p>
    <img src="{{ game.murderer.photo.url }}" alt="{{ game.murderer.photo.title }}" width="60" class="profile-thumb" />
    <p class="type-huge highlighted jollylodger">{{ 'game.status.murdererWon.convict' | trans({'%murderer%': game.murderer.name}) }}</p>
</div>
{% include "WinkMurderGameBundle:Game:status/_mostPopularDeath.html.twig" %}

src/WinkMurder/Bundle/GameBundle/Resources/views/Game/status/noMurderYet.html.twig
<div class="centered">
    <h1>{{ 'game.status.noMurderYet.heading' | trans }}</h1>
    <p>{{ 'game.status.noMurderYet.text' | trans }}</p>
</div>